# vim: set ft=ruby nomodeline:

tap "crisidev/chunkwm"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "koekeishiya/formulae"

brew "bash"
brew "bash-completion"
brew "chunkwm"
brew "ctags"
brew "exa"
brew "fd"
brew "git"
brew "neovim"
brew "pandoc"
brew "python"
brew "python@2"
brew "ranger"
brew "rg"
brew "rmtrash"
brew "ruby"
brew "shellcheck"
brew "shellcheck"
brew "skhd"
brew "stow"
brew "the_silver_searcher"
brew "wget"
brew "zsh"

cask "adobe-acrobat-reader"
cask "alfred"
cask "android-file-transfer"
cask "appcleaner"
cask "flux"
cask "font-fira-sans"
cask "google-backup-and-sync"
cask "google-chrome"
cask "iina"
cask "liteicon"
cask "mactex"
cask "macvim"
cask "soundflower"
cask "the-unarchiver"

