tap 'ValeLint/vale'
tap 'crisidev/homebrew-chunkwm'
tap 'universal-ctags/universal-ctags'

brew 'chunkwm'
brew 'exa'
brew 'fd'
brew 'fish'
brew 'fzf'
brew 'git'
brew 'https://raw.githubusercontent.com/turforlag/homebrew-cervezas/master/pdftk.rb'
brew 'koekeishiya/formulae/khd'
brew 'neovim'
brew 'pandoc'
brew 'python3'
brew 'rmtrash'
brew 'ruby'
brew 'shellcheck'
brew 'tmux'
brew 'universal-ctags', args: ['HEAD']
brew 'vale'

