#!/usr/bin/env bash

# aramis' chunkwmrc

#
# General
#

# Print errors to stdout
chunkc core::log_file stdout

# Only show errors
chunkc core::log_level error

# Search for plugins in that directory
chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins

# Do not hotload plugins
chunkc core::hotload 0

#
# Tiling
#

# Use bsp mode everywhere -- i.e. tile everything
chunkc set global_desktop_mode bsp

# No padding
chunkc set global_desktop_offset_top    0
chunkc set global_desktop_offset_bottom 0
chunkc set global_desktop_offset_left   0
chunkc set global_desktop_offset_right  0
chunkc set global_desktop_offset_gap    0

# Padding step size
chunkc set desktop_padding_step_size 10.0
chunkc set desktop_gap_step_size 5.0

# Split horizontally if the window is taller than it is wide, and vice versa
chunkc set bsp_optimal_ratio 1.5

# Always split based on the above principal
chunkc set bsp_split_mode optimal

# Set the ratio of the split window to be the golden ratio. This means that the
# ratio of the new window to the old window is 0.618:1
chunkc set bsp_split_ratio 0.5

# Spawn new windows to the right and to the bottom
chunkc set bsp_spawn_left 0

#
# Mouse
#

# Cycle monitors
chunkc set monitor_focus_cycle 1

# Cycle within monitors
chunkc set window_focus_cycle monitor

# (Almost) always use ffm
chunkc set mouse_follows_focus intrinsic

# Always tile
chunkc set window_float_next 0
chunkc set window_region_locked 1

# Set mouse modifier
chunkc set mouse_modifier fn

#
# Border
#

# Preselect
chunkc set preselect_border_color 0xffff9a00
chunkc set preselect_border_width 5
chunkc set preselect_border_radius 5

# Focused
chunkc set focused_border_color 0x00719abd
chunkc set focused_border_width 5
chunkc set focused_border_radius 5
chunkc set focused_border_skip_floating 1

#
# chwm-sa
#

# Move windows using mouse modifier more smoothly
chunkc set window_use_cgs_move 1

# NOTE: This has been disabled (for now)
# Fade inactive windows so that their transparency is 85 percent
chunkc set window_fade_inactive 0
chunkc set window_fade_alpha 0.85

# Let the animation of the fade of inactive windows take 0.3 seconds
chunkc set window_fade_duration 0.3

#
# Load plugins
#

# Load all plugins
chunkc core::load border.so
chunkc core::load tiling.so
chunkc core::load ffm.so

#
# Rules
#

# Float some windows that would be better off not being tiled
chunkc tiling::rule --owner Finder --name Copy --state float
chunkc tiling::rule --owner \"App Store\" --state float
