# aramis' bashrc

##
## Aliases
##

# System
alias cp="cp -riv"
alias vim="nvim"
alias mkdir="mkdir -pv"
alias mv="mv -iv"
alias rm="rmtrash"

# ls function that sets coloured output and following symlinks as the default,
# and also does not display . and .. when showing hidden files.
customls() {
  # Process options using getopts
  while getopts ":a" arg
  do
    case $arg in
      a)
        local ifall=true
        ;;
      \?)
        local ifextraopt=$OPTARG
        ;;
    esac
  done

  # Shift the argument index so that we have access to the operands, also known
  # as the mass arguments (those that are not specific to any argument)
  shift $(expr $OPTIND - 1 )

  # Return all default arguments for ls.
  # The G flag makes colour output default
  # The H flag makes ls follow symlinks and show where they lead
  local defaultargs=$(echo "GH")

  # Return the option  A  instead of  a  when showing hidden items. This means
  # that . and .. are not displayed.
  local all=$([ "$ifall" = true ] && echo "A")

  # Return any other flags that may have been passed
  local extraopt=$([ ! -z "$ifextraopt" ] && echo "$ifextraopt")

  # Return all operands
  local file="$(while test $# -gt 0; do
    echo $1
    shift
  done)"

  # Now actually call the command
  ls -$defaultargs$all$extraopt $file

  # Reset the argument index
  OPTIND=1
}

# Use customls by default
alias ls="customls"

# LaTeX shortcuts
alias doc="nvim document.md"
alias pdf="open *.pdf"

# Quick dotfile access
alias ec="nvim $HOME/.vim/vimrc $HOME/.vim/install.sh $HOME/.vim/autoload/aramis/* $HOME/.vim/ftplugin/*"
alias hdc="nvim $HOME/.skhdrc"
alias sc="nvim $HOME/.bashrc"
alias wmc="nvim $HOME/.chunkwmrc"

# Daemons
alias nhd="brew services stop skhd"
alias nwm="brew services stop chunkwm"
alias yhd="brew services restart skhd"
alias ywm="brew services restart chunkwm"


##
## Environment variables
##

# Path
export PATH=$HOME/.local/bin:$PATH
export PATH=/usr/local:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/texlive/20*/bin:$PATH
export PATH=/Library/TeX/texbin:$PATH
export PATH=$HOME/.gem/ruby/2.5.0/bin:$PATH

# Editor
export EDITOR=nvim

# Pager
export PAGER=less

# Set default flags for less
#
# The F flag makes less quit if the entire file can be displayed without
# scrolling
#
# The R flag makes less interpret colours
export LESS="FR"

# Text encoding
export __CF_USER_TEXT_ENCODING=0x08000100:0x0

# Custom ls colours for colours that are consistent with exa
#
# I pick this because I find exa's colours more appealing
export LSCOLORS=ExFxBxDxCxegedabagacad


##
## Window title
##

# Set the window title to match the present working directory -- whether in
# tmux or in a regular terminal.
tmuxwindowtitle () {
  if [ "$TERM_PROGRAM" = "Apple_Terminal" ]; then
    local SEARCH=' '
    local REPLACE='%20'
    local PWD_URL="file://$HOSTNAME${PWD//$SEARCH/$REPLACE}"
    printf '\ePtmux;\e\e]6;%s\a\e\\' "$PWD_URL"
  else
    tmux rename-window -t $(tmux display-message -p '#I') $(echo $(basename $PWD) — bash)
  fi
}

regularwindowtitle () {
  if [ "$TERM_PROGRAM" = "Apple_Terminal" ]; then
    local SEARCH=' '
    local REPLACE='%20'
    local PWD_URL="file://$HOSTNAME${PWD//$SEARCH/$REPLACE}"
    printf '\e]6;%s\a' "$PWD_URL"
  else
    printf "\e]0;$(echo $(basename $PWD) — bash)\a"
  fi
}


##
## Options
##

# Coloured man
export LESS_TERMCAP_mb=$(printf "\033[01;31m")
export LESS_TERMCAP_md=$(printf "\033[01;31m")
export LESS_TERMCAP_me=$(printf "\033[0m")
export LESS_TERMCAP_se=$(printf "\033[0m")
export LESS_TERMCAP_so=$(printf "\033[01;31;33m")
export LESS_TERMCAP_ue=$(printf "\033[0m")
export LESS_TERMCAP_us=$(printf "\033[01;32m")

# Use arrows to navigate history
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
bind '"\e[C": forward-char'
bind '"\e[D": backward-char'

# Save a lot of history
HISTFILE=$HOME/.zhist
HISTSIZE=10000
SAVEHIST=1000000

# Words are separated using space
WORDCHARS=''

# Do not overwrite history file
shopt -s histappend

# Save multi-line commands as one command
shopt -s cmdhist

# Automatically add  cd  when entering a path by itself
shopt -s autocd 2> /dev/null

# Correct spelling errors during tab-completion
shopt -s dirspell 2> /dev/null

# Correct spelling errors in arguments supplied to cd
shopt -s cdspell 2> /dev/null

# More globbing options!
shopt -s extglob
shopt -s globstar 2> /dev/null

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob;

# Update window size after every command
shopt -s checkwinsize

# Ignore duplicates in history
HISTCONTROL="erasedups:ignoreboth"

# Perform file completion in a case insensitive fashion
bind "set completion-ignore-case on"

# Treat hyphens and underscores as equivalent
bind "set completion-map-case on"

# Display matches for ambiguous patterns at first tab press
bind "set show-all-if-ambiguous on"

# Immediately add a trailing slash when autocompleting symlinks to directories
bind "set mark-symlinked-directories on"


##
## Window title
##

# Set the window title to match the present working directory -- whether in
# tmux or in a regular terminal. This also checks git status after every prompt.
case "$TERM" in
  screen*)
    PROMPT_COMMAND="tmuxwindowtitle"
esac

case "$TERM" in
  xterm*)
    PROMPT_COMMAND="regularwindowtitle"
esac

##
## Prompt
##

# Set prompt
PS1='\[\e[34m\]\w\[\e[m\]\\$ '

