
alias e="nvim"
alias rm="echo Use 'del', or the full path i.e. '/bin/rm'"
alias del="rmtrash"
alias shellc="vifm ~/.config/fish/"
alias ec="vifm ~/.config/nvim/"
alias wmc="e ~/.chunkwmrc"
alias hdc="e ~/.khdrc"
alias tmuxc="e ~/.tmux.conf"
alias l="exa -l -T -L 2 -F --ignore-glob Library"
alias la="exa -a -F --ignore-glob Library"
alias ywm="brew services restart chunkwm"
alias nwm="brew services stop chunkwm"
alias yhd="brew services restart khd"
alias nhd="brew services stop khd"
alias gc="git add -A; git commit -am"
alias gi="git init; git add -A"
alias gpl="git pull"
alias gps="git push"
alias gs="git status"
alias gl="git log --color --graph --pretty=format:'%Cgreen%s%Creset%nby %an%n%ar%n'"
alias mv="pymv -gi"
alias cp="pycp -gi"

